apiVersion: v1
kind: Pod
metadata:
  name: dhcp-server-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "dhcp-server-bridge-conf",
              "ips": [
 		"192.168.110.10/24"
                 ]
            }
    ]'
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: dhcptest
            operator: In
            values:
            - "true"          
  containers:
  - name: dhcp-server-pod
    image: quay.io/aneeshkp/dhcp-pod:latest
    ports:
    - containerPort: 67
      protocol: UDP
    - containerPort: 547
      protocol: UDP
