apiVersion: v1
kind: Pod
metadata:
  name: dhcp-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: dhcp-pod-bridge-conf
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: dhcptest
            operator: In
            values:
            - "true"   
  containers:
  - name: dhcp-sample-pod
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: dougbtv/centos-network
    ports:
    - containerPort: 80
